### ISSUE TITLE
Whitelist Pybricks

### ISSUE THREAD

**Issue by laurensvalk** [bricklife/Scrub#14]
Would it be possible to consider allowing the following two domains?

```
https://code.pybricks.com/
https://beta.pybricks.com/
```

And if so, do you think they would work?

![Photo 27-09-2022, 10 34 21](https://user-images.githubusercontent.com/12326241/192477690-4026a4e7-23a2-4a60-8fd9-d2a6aa116b9f.png)

If you like Pybricks, we could be honored to have it listed among the options. :smile: 

![Photo 27-09-2022, 10 42 14](https://user-images.githubusercontent.com/12326241/192480211-50ce8199-2ed0-4102-8ccb-8335aa5a5528.png)

**Comment by bricklife** [comment]
Thank you for your suggestion! Adding Pybricks's sites itself is very easy, but Scrub does not support Web Bluetooth API yet... If you are looking for any mobile app for Pybricks, Try [Bluefy](https://apps.apple.com/us/app/bluefy-web-ble-browser/id1492822055) instead.
